name: test-action
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request]
permissions:
  contents: read

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Check PR title
        env:
          title: "${{ github.event.pull_request.title }}"    #le titre est mis en tant que variable d'environement  !!   
        run: |
          if [[ $title =~ ^test ]]; then
          echo $title
          exit 0
          else
          echo "Pas content"
          exit 1
          fi
